# The repository needs to provide the following secrets
# - IoT Cloud Access - Settings and credentials required to connect an AWS IoT Thing
#   - MQTT_BROKER_ENDPOINT        MQTT broker host name
#   - IOT_THING_NAME              Client (device) name
#   - CLIENT_CERTIFICATE_PEM      Client (device) certificate
#   - CLIENT_PRIVATE_KEY_PEM      Client (device) private key

name: Build and Run
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  ARMLMD_LICENSE_FILE: /opt/data.dat
  ARM_TOOL_VARIANT: ult
  AC6_TOOLCHAIN_6_18_0: /opt/armcompiler/bin
  LD_LIBRARY_PATH: /opt/VHT
  AVH_PATH: /opt/VHT

jobs:
  build:
    name: Build and Run
    runs-on: samuel-avh-runner-15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          key: vcpkg-${{ github.run_id }}
          restore-keys: vcpkg-
          path: /root/.vcpkg

      - name: Cache packs
        uses: actions/cache@v3
        with:
          key: packs-${{ github.run_id }}
          restore-keys: packs-
          path: /root/.cache/arm/packs

      - name: Configure AWS IoT Thing Credentials
        env:
          MQTT_BROKER_ENDPOINT: ${{ secrets.MQTT_BROKER_ENDPOINT }}
          IOT_THING_NAME: ${{ secrets.IOT_THING_NAME }}
          CLIENT_CERTIFICATE_PEM: ${{ secrets.CLIENT_CERTIFICATE_PEM }}
          CLIENT_PRIVATE_KEY_PEM: ${{ secrets.CLIENT_PRIVATE_KEY_PEM }}
        run: |
          cd amazon-freertos/demos/include
          envsubst <aws_clientcredential.h.in >aws_clientcredential.h
          envsubst <aws_clientcredential_keys.h.in >aws_clientcredential_keys.h

      - name: Build the example for AVH
        run: |
          . <(curl https://aka.ms/vcpkg-init.sh -L)
          vcpkg activate
          cbuild Demo.csolution.yml --packs --update-rte --configuration .Debug+AVH -r

      - name: Run the example on AVH
        run: |
           export PATH=$PATH:$AVH_PATH
           ./run_example.sh
